version: '3.9'
services:
  web-app:
    container_name: Django
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "django-admin startproject app . && 
      python manage.py runserver 0.0.0.0:8000"


